version: '3.7'
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Mountain
    volumes:
      - /path/to/heimdall/config:/config
    ports:
      - 81:80
      - 443:443
    restart: unless-stopped
