version: '3.7'

services:
  sftp:
    image: ${SFTP_IMAGE}:${SFTP_VERSION}
    container_name: sftp-prod-local
    restart: always
    ports:
      - "2222:22"
    volumes:
      - ./config.json:/app/config/sftp.json:ro
